server:
  port: 8080
  tomcat:
    max-http-post-size: 104857600
    max-swallow-size: 104857600
  compression:
    enabled: true
    mime-types:
      - application/json
    min-response-size: 1024

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://demo-company.database.windows.net:1433;database=demo;
    username: parrysms@demo-company
    password: {your_password}
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: pocket-rental-api

logging:
  level:
    com: DEBUG


mybatis:
  type-aliases-package: cn.codesheep.springbt_mybatis_sqlserver.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
